name: Fetch IPTV List

on:
  schedule:
    - cron: '0 */6 * * *'  # 每 6 小时自动运行
  workflow_dispatch:  # 允许手动触发

jobs:
  fetch-iptv:
    runs-on: ubuntu-latest
    steps:
      - name: 获取 GitHub 仓库
        uses: actions/checkout@v3
      
      - name: 安装 Python 依赖
        run: pip install requests
      
      - name: 运行 IPTV 获取脚本
        run: python iptv_fetch.py

      - name: 提交 IPTV 数据
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add iptv.txt
          git commit -m "更新 IPTV 频道列表" || exit 0
          git push
